[package]
name = "immich-dlna-proxy"
version = "0.1.0"
edition = "2024"
description = "Immich DLNA proxy"
repository = "https://github.com/ku1ik/immich-dlna-proxy"
homepage = "https://github.com/ku1ik/immich-dlna-proxy"
readme = "README.md"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0"
